name: 'Thank You Action'
description: 'Say "Thank You" to new pull requests'
author: '[Your Name]'
inputs:
        userId:
          type: string
          description: UserId for PRM TOKEN
          required: true
        password:
          type: string
          description: password for PRM TOKEN
          required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
