name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout and run Script
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          format: "csv"
      - name: Run step if any of the listed files above change
        run: |
          for file in ${{ steps.changed-files-specific.outputs. all_changed_files }}; do
            echo "$file was modified"
          done  
          uses: ./
      - name: move processed files
        run: |
           mv data/*.csv data/processed/
      - name: Commit files
        run: |
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              git commit -m "generated"
              git push
