name: Test2

on:
  workflow_dispatch:
    inputs:
        name:
          type: string
          description: UserId for PRM TOKEN
          required: true
        password:
          type: string
          description: password for PRM TOKEN
          required: true


jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.checkFileExists.outputs.changed}}
    steps:
     
      - name: Checkout and run Script
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run step if any of the listed files above change
        id: CheckFileExists
        run: |
              INPUTDIR=data
                    for i in $INPUTDIR/*.csv
                    do
                      echo "$i" # action on existing file, here echo.
                      echo "changed=true" >> $GITHUB_OUTPUT
                      echo ${{ inputs.userId }}
                      break
                    done
      - name: Run Script
        if: steps.checkFileExists.outputs.changed == 'true'
        uses: ./
        with:
          userId: ${{ inputs.name }}
          password: ${{ inputs.password }}
      - name: move processed files
        if: steps.checkFileExists.outputs.changed == 'true' 
        run: |
           mv data/*.csv data/processed/
      - name: Commit files
        if: steps.checkFileExists.outputs.changed == 'true' 
        run: |
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              git commit -m "generated"
              git push
